### ISSUE TITLE
Prepare for blog

### ISSUE THREAD

**Issue by JoepKockelkorn** [JoepKockelkorn/joepkockelkorn.com#25]
# Todo

- [x] Move to Vercel
- [x] stale-while-revalidate?
- [x] SEO stuff (sitemap, robots.txt)
- [x] Check twitter preview
- [x] Google Search Console

**Comment by JoepKockelkorn** [comment]
<img width="692" alt="image" src="https://user-images.githubusercontent.com/12891645/230487669-e8f7d544-f25b-46ea-8ff0-769fa4b4896f.png">
Works!

**Comment by JoepKockelkorn** [comment]
Done
